sonar.projectKey=api-rest
sonar.projectName=api-rest
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=http://localhost:9000
sonar.login=squ_d0ee581519d1a87991a90fe7a02e74d6f7328d31